### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by MartinP7r** [jayhickey/Cirrus#1]
Hi @jayhickey,  

first off thank you for providing this package! It already helped me a lot.

I have a quick question about your API:  
Is there a reason behind `delete` and `upload` accepting `Array`s
https://github.com/jayhickey/Cirrus/blob/07882fcda9e7ab8a6f4f59fb21f2535a74e47224/Sources/Cirrus/SyncEngine.swift#L131

while the model changes are passing `Set`s?
https://github.com/jayhickey/Cirrus/blob/07882fcda9e7ab8a6f4f59fb21f2535a74e47224/Sources/Cirrus/SyncEngine.swift#L10

Cheers,
Martin

**Comment by jayhickey** [comment]
Hey there, I'm glad to hear you find this helpful 😀 

Good question, yes there is a reason: with an array you have the flexibility to call `upload` and `delete` with multiple records/models that have the same identifier. The ordering means CloudKit can queue the individual record changes and know what the most recent model is for a given identifier. If these were sets you would get undefined behavior if you tried to upload multiple models with the same identifier (unless you did something like mark the identifier as your sole equality comparison for the set, which is probably not a good idea).

Making them sets on the model change side is primarily for easy of use and to avoid the need to dedupe models with the same identifier on the receiving end. When you receive changes you will just get the latest version of a given model, so order doesn't really matter.

**Comment by MartinP7r** [comment]
Thank you for responding so quick with a detailed explanation!  

I didn't really think of passing multiple records for the same identifier. Thank you for clearing that up.  
This probably ties into buffering multiple records with the same id into your `uploadContext` when the network is unavailable, etc.?  
(Sorry if that makes no sense, I haven't dug to far into the source code, yet)

**Comment by jayhickey** [comment]
Yes exactly, you're spot on. Offline queuing is one possible use case where you could encounter this situation of trying to upload multiple records with the same identifier. 

Feel free to re-open this issue if you have any additional followup questions around this!
