### ISSUE TITLE
Sync won't update remote record when optional date is nil

### ISSUE THREAD

**Issue by marcelmendesfilho** [jayhickey/Cirrus#11]
Hi there!

My app has a model with an optional date attribute.
The cloud sync happens ok when the app sets a value to that date, but when the appI sets a nil to that date and calls upload, sync doesn't update the remote (the iCloud record has the old date).
Soon after upload(), the modelsChanged.sink gets called with an update change event with the object with its original date.
Any ideas?

Thanks

**Comment by marcelmendesfilho** [comment]
[Solved] To work around this, I had to add custom encoder/decoder entries for all optional dates, storing them on Data properties.

**Comment by huanglins** [comment]
Hello, is there a reference for custom codec implementation of this piece?  For example, date? , [String]?

**Comment by marcelmendesfilho** [comment]
Hi there! See my answer to your other question you've posted here. It has an example with Date? but the concept applies to [String]? or any other optional.

**Comment by dknchris** [comment]
Pull request #12 should fix the issue in the library. @marcelmendesfilho Can you please give it a go at your end?
