### ISSUE TITLE
How to retrieve all data in CloudKit when reinstalling the app after it has been deleted？

### ISSUE THREAD

**Issue by BearChao** [jayhickey/Cirrus#8]
Hi @jayhickey , thanks for your great work! 

I want to retrieve all data in CloudKit when reinstalling the app, is there a way to retrieve all cloud records and compare them with local ones?

**Comment by jayhickey** [comment]
On a delete and re-install, the first time you connect to iCloud the `modelsChanged` publisher will publish all the cloud records for you to store and allow you to compare them to anything you might have locally. Hope that helps!
